"""Command line tools for the kinematics test bench."""

from __future__ import annotations

import argparse
import math
import os
import sys
import time
from typing import List, Optional

import numpy as np

from arm_lab_model.config import load_config
from arm_lab_model.kinematics import ArmModel

from . import iso9283 as iso
from .cartesian import plan_line
from .collision import CollisionChecker, build_allowed_collisions
from .ik import IKSolver
from .singularity import classify, metrics, speed_capability
from .safety import build as build_safety, summarise as summarise_safety
from .topp import parameterise
from .workspace import TOOL_DOWN, build_map, summarise


def _base(p: argparse.ArgumentParser) -> None:
    p.add_argument('--config', default=None, help='path to arm_config.yaml')
    p.add_argument('--ee-mass', type=float, default=None)
    p.add_argument('--gravity', type=float, default=None)


def _load(args):
    cfg = load_config(args.config, ee_mass=getattr(args, 'ee_mass', None),
                      gravity=getattr(args, 'gravity', None))
    return cfg, ArmModel(cfg)


def _checker(model: ArmModel, samples: int = 800) -> CollisionChecker:
    acm = build_allowed_collisions(model, samples=samples)
    return CollisionChecker(model, allowed=acm['always'])


# --------------------------------------------------------------- ik_check
def ik_check_main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog='ik_check',
        description='FK/IK round-trip validation: sample poses, solve them back.')
    _base(p)
    p.add_argument('--samples', type=int, default=200)
    p.add_argument('--seed', type=int, default=0)
    p.add_argument('--position-only', action='store_true')
    args = p.parse_args(argv)
    cfg, model = _load(args)
    solver = IKSolver(model)
    rng = np.random.default_rng(args.seed)

    ok = 0
    pos_err, ori_err, elapsed = [], [], []
    for k in range(args.samples):
        q = rng.uniform(model.lower * 0.9, model.upper * 0.9)
        fs = model.frames(q)
        t0 = time.perf_counter()
        res = solver.solve(fs.tcp, None if args.position_only else fs.tcp_R,
                           rng=np.random.default_rng(k))
        elapsed.append(time.perf_counter() - t0)
        ok += res.success
        pos_err.append(res.position_error)
        ori_err.append(res.orientation_error_deg)

    pos_err = np.array(pos_err)
    ori_err = np.array(ori_err)
    print(f'\nFK/IK round trip  --  {cfg.name}')
    print(f'  task            : {"position only" if args.position_only else "full 6-DOF pose"}')
    print(f'  samples         : {args.samples} (targets generated by forward '
          'kinematics, so every one is reachable by construction)')
    print(f'  solved          : {ok}/{args.samples}  ({ok / args.samples * 100:.1f} %)')
    print(f'  position error  : median {np.median(pos_err) * 1e6:.2f} um, '
          f'95th {np.percentile(pos_err, 95) * 1e3:.3f} mm, '
          f'max {pos_err.max() * 1e3:.3f} mm')
    if not args.position_only:
        print(f'  orientation err : median {np.median(ori_err) * 1e3:.2f} mdeg, '
              f'95th {np.percentile(ori_err, 95):.4f} deg, '
              f'max {ori_err.max():.4f} deg')
    print(f'  solve time      : median {np.median(elapsed) * 1e3:.0f} ms, '
          f'max {max(elapsed) * 1e3:.0f} ms')
    near = int(np.sum((pos_err < 1e-3) & (ori_err < 0.1)))
    print(f'  within 1 mm/0.1 deg : {near}/{args.samples} '
          f'({near / args.samples * 100:.1f} %)')
    return 0 if ok >= 0.9 * args.samples else 1


# -------------------------------------------------------------- workspace
def workspace_main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog='workspace',
        description='Map the reachable, tool-down and dexterous workspace.')
    _base(p)
    p.add_argument('--samples', type=int, default=40000)
    p.add_argument('--nr', type=int, default=34)
    p.add_argument('--nz', type=int, default=26)
    p.add_argument('--orientations', type=int, default=6)
    p.add_argument('--quick', action='store_true',
                   help='coarse and fast: fewer cells and orientations')
    p.add_argument('--no-collision', action='store_true',
                   help='skip self-collision filtering')
    p.add_argument('--no-dexterity', action='store_true')
    p.add_argument('--save', default=None, help='write the map to an .npz file')
    args = p.parse_args(argv)
    cfg, model = _load(args)
    if args.quick:
        args.samples, args.nr, args.nz, args.orientations = 12000, 20, 16, 3

    checker = None if args.no_collision else _checker(model)

    def progress(done, total):
        print(f'\r  orientation sweep {done}/{total} cells',
              end='', file=sys.stderr, flush=True)

    t0 = time.time()
    wmap = build_map(model, samples=args.samples, nr=args.nr, nz=args.nz,
                     orientations=args.orientations,
                     collision_checker=checker,
                     dexterity=not args.no_dexterity, progress=progress)
    print('\r' + ' ' * 50 + '\r', end='', file=sys.stderr)
    print(summarise(model, wmap))
    print(f'\n  ({time.time() - t0:.0f} s)')
    if args.save:
        np.savez(args.save, r_edges=wmap.r_edges, z_edges=wmap.z_edges,
                 reachable=wmap.reachable, tool_down=wmap.tool_down,
                 dexterity=wmap.dexterity, sweep_angle=wmap.sweep_angle)
        print(f'  saved to {args.save}')
    return 0


# ------------------------------------------------------------ singularity
def singularity_main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog='singularity',
        description='Conditioning and singularity analysis of the test poses.')
    _base(p)
    p.add_argument('--scan', action='store_true',
                   help='also sweep the workspace for singular regions')
    p.add_argument('--samples', type=int, default=4000)
    args = p.parse_args(argv)
    cfg, model = _load(args)

    W = 100
    print('\n' + '=' * W)
    print('  CONDITIONING AT THE TEST POSES')
    print('=' * W)
    print(f'{"pose":<12}{"sigma_min":>11}{"cond":>9}{"manip_v":>10}'
          f'{"speed best":>12}{"speed worst":>13}   diagnosis')
    print('-' * W)
    for name in cfg.test_poses:
        try:
            q = model.resolve_pose(name)
        except Exception as exc:                        # noqa: BLE001
            print(f'{name:<12} could not resolve: {exc}')
            continue
        m = metrics(model, q)
        s = speed_capability(model, q)
        note = m.kind if m.is_singular else classify(model, q)
        print(f'{name:<12}{m.sigma_min_full:>11.4f}{m.condition_full:>9.1f}'
              f'{m.manipulability_v:>10.4f}{s["best_direction"]:>12.2f}'
              f'{s["worst_direction"]:>13.3f}   {note}')
    print('-' * W)
    print('  speed best/worst are TCP m/s in the easiest and hardest direction.')
    print('  The worst-direction figure is the one a speed specification has to')
    print('  survive: it collapses to zero at a singularity.')

    if args.scan:
        rng = np.random.default_rng(0)
        sigmas, singular = [], 0
        for _ in range(args.samples):
            q = rng.uniform(model.lower, model.upper)
            m = metrics(model, q)
            sigmas.append(m.sigma_min_full)
            singular += m.is_singular
        sigmas = np.array(sigmas)
        print('\n' + '=' * W)
        print(f'  WORKSPACE SCAN  ({args.samples} random configurations)')
        print('=' * W)
        print(f'  singular (sigma_min < 0.02) : {singular} '
              f'({singular / args.samples * 100:.1f} %)')
        for pct in (5, 25, 50, 75, 95):
            print(f'  sigma_min {pct:>2}th percentile   : '
                  f'{np.percentile(sigmas, pct):.4f}')
    return 0


# ----------------------------------------------------------------- iso9283
def iso9283_main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog='iso9283',
        description='ISO 9283 pose accuracy, repeatability and path accuracy.')
    _base(p)
    p.add_argument('--cycles', type=int, default=iso.DEFAULT_CYCLES)
    p.add_argument('--payload', type=float, default=0.0)
    p.add_argument('--cube-side', type=float, default=None)
    p.add_argument('--cube-centre', type=float, nargs=3, default=None)
    p.add_argument('--unit-seed', type=int, default=0,
                   help='which built arm to test; a different seed is a '
                        'different unit off the same drawing')
    p.add_argument('--units', type=int, default=1,
                   help='test several units and report the spread')
    args = p.parse_args(argv)
    cfg, model = _load(args)

    results = []
    for unit in range(max(args.units, 1)):
        result = iso.run(cfg, centre=args.cube_centre, side=args.cube_side,
                         cycles=args.cycles, payload=args.payload,
                         unit_seed=args.unit_seed + unit)
        results.append(result)
        if args.units == 1:
            print(iso.render(result, cfg))

    if args.units > 1:
        print(f'\n  {args.units} BUILT UNITS, {args.cycles} cycles each')
        print('  ' + '-' * 60)
        print(f'  {"unit":<8}{"AP mm":>10}{"RP mm":>10}{"AP deg":>10}')
        for i, r in enumerate(results):
            print(f'  {i:<8}{r.worst_AP * 1000:>10.2f}{r.worst_RP * 1000:>10.2f}'
                  f'{r.worst_AP_orientation:>10.3f}')
        aps = np.array([r.worst_AP for r in results])
        print('  ' + '-' * 60)
        print(f'  accuracy across units: mean {aps.mean() * 1000:.2f} mm, '
              f'worst {aps.max() * 1000:.2f} mm')
        print('  Spread across units comes from the machining and assembly '
              'tolerances;\n  each unit is individually repeatable.')

    worst = max(r.worst_AP for r in results)
    return 0 if worst <= float(
        cfg.spec_targets.get('raw_positioning_accuracy', 0.01)) else 1


# --------------------------------------------------------------- cartesian
def cartesian_main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog='cartesian_plan',
        description='Plan a straight-line TCP move and check the speed limit.')
    _base(p)
    p.add_argument('--from-pose', default='home')
    p.add_argument('--to', type=float, nargs=3, required=True,
                   metavar=('X', 'Y', 'Z'))
    p.add_argument('--speed', type=float, default=None)
    p.add_argument('--accel', type=float, default=None)
    p.add_argument('--compare-joint-space', action='store_true',
                   help='show what the joint-space controller would do instead')
    args = p.parse_args(argv)
    cfg, model = _load(args)

    q0 = model.resolve_pose(args.from_pose)
    path = plan_line(model, q0, np.array(args.to), TOOL_DOWN,
                     speed=args.speed, accel=args.accel)
    limit = args.speed if args.speed is not None else float(
        cfg.raw.get('motion', {}).get('cartesian_speed', 0.2))

    print(f'\n  straight line from "{args.from_pose}" to '
          f'({args.to[0]:.3f}, {args.to[1]:.3f}, {args.to[2]:.3f})')
    print(f'  feasible          : {path.feasible}')
    for note in path.notes:
        print(f'    - {note}')
    if not path.feasible:
        return 1
    straight = float(np.linalg.norm(np.array(args.to) - model.fk(q0)))
    print(f'  waypoints         : {len(path.times)}')
    print(f'  duration          : {path.duration:.2f} s')
    print(f'  path length       : {path.path_length:.4f} m '
          f'(straight line {straight:.4f} m)')
    print(f'  commanded speed   : {limit:.3f} m/s')
    print(f'  peak TCP speed    : {path.peak_tcp_speed:.3f} m/s')
    print(f'  joint speed usage : '
          f'{100 * np.max(np.abs(path.joint_speeds) / model.velocity_limits):.0f} %')

    if args.compare_joint_space:
        q1 = path.joints[-1]
        duration = straight / limit
        steps = 200
        alpha = np.linspace(0, 1, steps)
        # Cubic ease, which is what a spline interpolator produces.
        blend = 3 * alpha ** 2 - 2 * alpha ** 3
        joint_path = q0 + (q1 - q0) * blend[:, None]
        times = alpha * duration
        tcp = np.array([model.fk(q) for q in joint_path])
        speeds = np.linalg.norm(np.gradient(tcp, times, axis=0), axis=1)
        length = float(np.linalg.norm(np.diff(tcp, axis=0), axis=1).sum())
        print('\n  the same move through the joint-space controller:')
        print(f'    path length     : {length:.4f} m '
              f'({(length / straight - 1) * 100:+.1f} % vs the straight line)')
        print(f'    peak TCP speed  : {speeds.max():.3f} m/s '
              f'({speeds.max() / limit:.2f}x the commanded average)')
        print('    A joint-space spline bows away from the line and peaks above')
        print('    its own mean, so trajectory timing alone cannot enforce a')
        print('    Cartesian speed limit.')
    return 0


# -------------------------------------------------------------------- topp
def topp_main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog='topp',
        description='Time-optimal timing of a path under speed, acceleration '
                    'and actuator torque limits.')
    _base(p)
    p.add_argument('--from-pose', default='home')
    p.add_argument('--to', type=float, nargs=3, required=True,
                   metavar=('X', 'Y', 'Z'))
    p.add_argument('--payload', type=float, default=0.0)
    p.add_argument('--torque-fractions', type=float, nargs='*',
                   default=[1.0, 0.75, 0.5])
    args = p.parse_args(argv)
    cfg, model = _load(args)

    q0 = model.resolve_pose(args.from_pose)
    path = plan_line(model, q0, np.array(args.to), TOOL_DOWN)
    if not path.feasible:
        print('  the straight line is not reachable; nothing to time')
        return 1
    joints = path.joints[::max(len(path.joints) // 60, 1)]
    spec_speed = float(cfg.raw.get('motion', {}).get('cartesian_speed', 0.2))

    print(f'\n  path: {len(joints)} waypoints over {path.path_length:.3f} m')
    print(f'\n  {"torque budget":<18}{"time s":>9}{"peak TCP m/s":>15}'
          f'{"peak torque":>13}   binding constraint')
    print('  ' + '-' * 86)
    base = parameterise(model, joints, tcp_speed_limit=spec_speed)
    print(f'  {"at spec speed":<18}{base.duration:>9.2f}'
          f'{base.peak_tcp_speed:>15.3f}'
          f'{100 * np.max(np.abs(base.torques) / model.torque_limits):>12.0f}%'
          f'   {base.notes[0].split(": ", 1)[-1]}')
    for fraction in args.torque_fractions:
        r = parameterise(model, joints, torque_fraction=fraction)
        if not r.feasible:
            print(f'  {fraction * 100:>3.0f} % of peak     '
                  f'{"infeasible":>9}   {r.notes[-2]}')
            continue
        print(f'  {fraction * 100:>3.0f} % of peak{"":<6}{r.duration:>9.2f}'
              f'{r.peak_tcp_speed:>15.3f}'
              f'{100 * np.max(np.abs(r.torques) / model.torque_limits):>12.0f}%'
              f'   {r.notes[0].split(": ", 1)[-1]}')
    print('  ' + '-' * 86)
    print('  "at spec speed" holds the TCP to the configured Cartesian limit;')
    print('  the rest ask how fast the arm could go if only the actuators and')
    print('  the acceleration ceiling had a say.')
    return 0


# --------------------------------------------------------------- collision
def collision_main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog='collision_check',
        description='Self-collision check of the test poses, plus the derived '
                    'allowed-collision matrix.')
    _base(p)
    p.add_argument('--samples', type=int, default=2000)
    args = p.parse_args(argv)
    cfg, model = _load(args)

    acm = build_allowed_collisions(model, samples=args.samples)
    checker = CollisionChecker(model, allowed=acm['always'])
    print(f'\n  allowed-collision matrix from {args.samples} random poses')
    print('  always in contact (capsules overlap by construction, disabled):')
    for a, b in sorted(acm['always']) or [('none', '')]:
        print(f'    {a} / {b}')
    print(f'  never in contact: {len(acm["never"])} pairs')
    print(f'  genuinely variable: {len(acm["sometimes"])} pairs')

    print('\n  test poses:')
    bad = 0
    for name in cfg.test_poses:
        try:
            q = model.resolve_pose(name)
        except Exception as exc:                        # noqa: BLE001
            print(f'    {name:<12} could not resolve: {exc}')
            continue
        report = checker.check(q)
        bad += report.in_collision
        detail = ', '.join(f'{a}/{b}' for a, b, _ in report.pairs) or ''
        if report.ground:
            detail += ' ground:' + ','.join(n for n, _ in report.ground)
        print(f'    {name:<12} {"COLLISION" if report.in_collision else "clear":<10}'
              f' min clearance {report.min_clearance * 1000:+7.1f} mm  {detail}')

    rng = np.random.default_rng(0)
    hits = sum(0 if checker.is_free(rng.uniform(model.lower, model.upper)) else 1
               for _ in range(args.samples))
    print(f'\n  {hits}/{args.samples} random configurations self-collide '
          f'({hits / args.samples * 100:.0f} %), which is why a planner needs '
          'this check')
    return 1 if bad else 0


# ---------------------------------------------------------------- moveit
def moveit_main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog='moveit_gen',
        description='Generate a MoveIt 2 configuration from the arm config.')
    _base(p)
    p.add_argument('-o', '--output', default='moveit_config',
                   help='directory to write into')
    p.add_argument('--samples', type=int, default=1500)
    args = p.parse_args(argv)
    cfg, _ = _load(args)
    from .moveit_gen import write_config
    paths = write_config(cfg, args.output, samples=args.samples)
    print(f'\n  MoveIt configuration written to {os.path.abspath(args.output)}')
    for path in paths:
        print(f'    {os.path.basename(path)}')
    print('\n  Pair it with the URDF from `ros2 run arm_lab_model urdf_gen`.')
    print('  The disable_collisions list is the same allowed-collision matrix')
    print('  the capsule checker derives, so the two cannot drift apart.')
    return 0


# ---------------------------------------------------------------- safety
def safety_main(argv: Optional[List[str]] = None) -> int:
    p = argparse.ArgumentParser(
        prog='safety_map',
        description='Map joint torque, power and singularity zones over the '
                    'working plane.')
    _base(p)
    p.add_argument('--payload', type=float, default=None,
                   help='load at the TCP, kg; defaults to the rated payload')
    p.add_argument('--nr', type=int, default=30)
    p.add_argument('--nz', type=int, default=22)
    p.add_argument('--samples', type=int, default=20000)
    p.add_argument('--quick', action='store_true')
    args = p.parse_args(argv)
    cfg, model = _load(args)
    payload = (args.payload if args.payload is not None
               else float(cfg.spec_targets.get('payload_at_full_reach', 2.0)))
    if args.quick:
        args.nr, args.nz, args.samples = 22, 16, 10000

    def progress(done, total):
        print(f'\r  probing {done}/{total} cells', end='', file=sys.stderr,
              flush=True)

    smap = build_safety(model, payload=payload, nr=args.nr, nz=args.nz,
                        samples=args.samples, collision_checker=_checker(model),
                        progress=progress)
    print('\r' + ' ' * 40 + '\r', end='', file=sys.stderr)
    print(summarise_safety(model, smap))
    counts = smap.zone_counts()
    return 1 if (counts['over torque'] or counts['self-collision']) else 0
