"""Generate a MoveIt 2 configuration from the same YAML.

The SRDF's `disable_collisions` list is exactly the allowed-collision matrix the
capsule checker already derives by sampling, so the two stay consistent instead
of being maintained separately.
"""

from __future__ import annotations

import os
from typing import Dict, List, Optional
from xml.sax.saxutils import escape

import yaml

from arm_lab_model.config import ArmConfig
from arm_lab_model.kinematics import ArmModel

from .collision import build_allowed_collisions

ARM_GROUP = 'arm'
GRIPPER_GROUP = 'gripper'


class _NoAliasDumper(yaml.SafeDumper):
    """MoveIt's parameter loading, like rcl's, rejects YAML aliases."""

    def ignore_aliases(self, data):
        return True


def build_srdf(cfg: ArmConfig, samples: int = 1500) -> str:
    model = ArmModel(cfg)
    acm = build_allowed_collisions(model, samples=samples)
    joints = cfg.joint_names
    tip = 'tcp_link'

    out: List[str] = ['<?xml version="1.0"?>',
                      f'<!-- generated by arm_lab_kinematics from {cfg.source_path} -->',
                      f'<robot name="{escape(cfg.name)}">', '']
    out.append(f'  <group name="{ARM_GROUP}">')
    out.append(f'    <chain base_link="base_link" tip_link="{tip}"/>')
    out.append('  </group>')

    fingers = cfg.end_effector.finger_joint_names
    if fingers:
        out.append(f'  <group name="{GRIPPER_GROUP}">')
        for name in fingers:
            out.append(f'    <joint name="{escape(name)}"/>')
        out.append('  </group>')
        out.append(f'  <end_effector name="{cfg.end_effector.name}" '
                   f'parent_link="{tip}" group="{GRIPPER_GROUP}"/>')

    for pose_name, spec in cfg.test_poses.items():
        try:
            q = model.resolve_pose(spec)
        except Exception:                      # noqa: BLE001  (auto poses may fail)
            continue
        out.append(f'  <group_state name="{escape(pose_name)}" '
                   f'group="{ARM_GROUP}">')
        for name, value in zip(joints, q):
            out.append(f'    <joint name="{escape(name)}" value="{value:.6f}"/>')
        out.append('  </group_state>')

    out.append('  <virtual_joint name="world_joint" type="fixed" '
               'parent_frame="world" child_link="base_link"/>')

    out.append('')
    out.append('  <!-- pairs that are in contact in essentially every pose: the '
               'capsule model is conservative around the short wrist links -->')
    for a, b in sorted(acm['always']):
        out.append(f'  <disable_collisions link1="{escape(a)}" '
                   f'link2="{escape(b)}" reason="Always"/>')
    out.append('  <!-- pairs that never come close in any sampled pose -->')
    for a, b in sorted(acm['never']):
        out.append(f'  <disable_collisions link1="{escape(a)}" '
                   f'link2="{escape(b)}" reason="Never"/>')
    names = [j.link.name for j in cfg.joints]
    for i in range(len(names) - 1):
        out.append(f'  <disable_collisions link1="{escape(names[i])}" '
                   f'link2="{escape(names[i + 1])}" reason="Adjacent"/>')
    out.append('</robot>')
    return '\n'.join(out) + '\n'


def build_kinematics(cfg: ArmConfig) -> Dict:
    return {ARM_GROUP: {
        'kinematics_solver': 'kdl_kinematics_plugin/KDLKinematicsPlugin',
        'kinematics_solver_search_resolution': 0.005,
        'kinematics_solver_timeout': 0.05,
        'kinematics_solver_attempts': 3,
    }}


def build_joint_limits(cfg: ArmConfig) -> Dict:
    motion = cfg.raw.get('motion', {})
    accel = float(motion.get('joint_acceleration', 3.0))
    limits = {}
    for joint in cfg.joints:
        limits[joint.name] = {
            'has_velocity_limits': True,
            'max_velocity': float(joint.usable_speed),
            'has_acceleration_limits': True,
            'max_acceleration': accel,
            'has_effort_limits': True,
            'max_effort': float(joint.effort_limit),
        }
    for name in cfg.end_effector.finger_joint_names:
        limits[name] = {
            'has_velocity_limits': True,
            'max_velocity': float(cfg.end_effector.grip_speed),
            'has_acceleration_limits': True,
            'max_acceleration': 1.0,
            'has_effort_limits': True,
            'max_effort': float(cfg.end_effector.grip_force_max),
        }
    return {'joint_limits': limits}


def build_controllers(cfg: ArmConfig) -> Dict:
    names = ['arm_controller']
    controllers: Dict = {
        'arm_controller': {
            'type': 'FollowJointTrajectory',
            'action_ns': 'follow_joint_trajectory',
            'default': True,
            'joints': list(cfg.joint_names),
        }
    }
    if cfg.end_effector.finger_joint_names:
        names.append('gripper_controller')
        controllers['gripper_controller'] = {
            'type': 'GripperCommand',
            'action_ns': 'gripper_cmd',
            'default': True,
            'joints': list(cfg.end_effector.finger_joint_names),
        }
    return {
        'moveit_simple_controller_manager': dict(
            {'controller_names': names}, **controllers),
        'moveit_controller_manager':
            'moveit_simple_controller_manager/MoveItSimpleControllerManager',
    }


def build_planning(cfg: ArmConfig) -> Dict:
    return {
        'planning_pipelines': ['ompl'],
        'default_planning_pipeline': 'ompl',
        'ompl': {
            'planning_plugins':
                ['ompl_interface/OMPLPlanner'],
            ARM_GROUP: {
                'planner_configs': ['RRTConnectkConfigDefault'],
            },
            'planner_configs': {
                'RRTConnectkConfigDefault': {
                    'type': 'geometric::RRTConnect',
                    'range': 0.0,
                },
            },
        },
    }


def write_config(cfg: ArmConfig, directory: str, samples: int = 1500) -> List[str]:
    """Write the MoveIt config files; returns the paths written."""
    os.makedirs(directory, exist_ok=True)
    written: List[str] = []

    srdf_path = os.path.join(directory, f'{cfg.name}.srdf')
    with open(srdf_path, 'w') as fh:
        fh.write(build_srdf(cfg, samples=samples))
    written.append(srdf_path)

    header = (f'# generated by arm_lab_kinematics from {cfg.source_path}\n'
              '# DO NOT EDIT: change the YAML config and regenerate\n')
    for filename, data in (('kinematics.yaml', build_kinematics(cfg)),
                           ('joint_limits.yaml', build_joint_limits(cfg)),
                           ('moveit_controllers.yaml', build_controllers(cfg)),
                           ('ompl_planning.yaml', build_planning(cfg))):
        path = os.path.join(directory, filename)
        with open(path, 'w') as fh:
            fh.write(header)
            yaml.dump(data, fh, Dumper=_NoAliasDumper, sort_keys=False,
                      default_flow_style=False)
        written.append(path)
    return written
