"""Rebuild source-derived references and diagram embeds; --check detects drift.

Uses AST rather than importing ROS/GUI modules. Run from any directory.
"""
from __future__ import annotations

import argparse
import ast
import os
from pathlib import Path
import re
import sys
from unittest.mock import patch

import yaml

ROOT = Path(__file__).resolve().parents[1]
HEADER = '<!-- AUTO-GENERATED by tools/build_docs.py. Do not edit this file directly. -->\n'


def cell(value):
    return str(value).replace('|', '&#124;').replace('\n', ' ')


def tree(path):
    return ast.parse(path.read_text())


def source_link(path):
    return '../' + path.relative_to(ROOT).as_posix()


def commands():
    lines = ['# Command and launch reference', '', HEADER,
             'Read [Getting started](GETTING_STARTED.md) for installation and',
             '[the runbook](RUNBOOK.md) for runtime checks. Tables below are extracted',
             'from setup scripts and launch declarations; source links identify the implementation.', '',
             '## Installed executables', '',
             'Core model commands work in the documented Python environment. GUI and ROS',
             'node commands require the ROS workspace. Use `ros2 run PACKAGE COMMAND`',
             'for ROS installs; use `COMMAND --help` for offline CLI options.', '',
             '| Package | Executable | Python entry point |', '|---|---|---|']
    for setup in sorted((ROOT / 'src').glob('*/setup.py')):
        for node in ast.walk(tree(setup)):
            if not isinstance(node, ast.Call) or not isinstance(node.func, ast.Name) or node.func.id != 'setup':
                continue
            keyword = next(k for k in node.keywords if k.arg == 'entry_points')
            for entry in ast.literal_eval(keyword.value)['console_scripts']:
                name, target = (v.strip() for v in entry.split('=', 1))
                package = setup.parent.name
                module, function = target.split(':')
                module_path = setup.parent / (module.replace('.', '/') + '.py')
                lines.append(f'| `{package}` | `{name}` | [{target}]({source_link(module_path)}) |')
    lines += ['', '## MuJoCo subcommands', '',
              'The options below come from each subparser at runtime; no engine is started.', '']
    # Only this ROS-free module is imported, and --help exits before loading a model.
    import contextlib
    import io
    sys.path.insert(0, str(ROOT / 'src' / 'arm_lab_model'))
    from arm_lab_model.mujoco_backend import main
    for command in ('export', 'check', 'simulate', 'smoke'):
        output = io.StringIO()
        with (contextlib.redirect_stdout(output), patch.object(sys, 'argv', ['robot_test']),
              patch.dict(os.environ, {'COLUMNS': '80'})):
            try:
                main([command, '--help'])
            except SystemExit as exc:
                if exc.code != 0:
                    raise
        help_text = output.getvalue()
        lines += [f'### robot_test {command}', '', '```text', help_text.rstrip(), '```', '']
    from arm_lab_model.pipeline_cli import main as pipeline_main
    lines += ['## General robot pipeline subcommands', '',
              'Use a versioned project manifest; legacy arm commands retain their original input.', '']
    for command in ('build', 'analyze', 'reference-check', 'simulate', 'replay', 'compare'):
        output = io.StringIO()
        with (contextlib.redirect_stdout(output), patch.object(sys, 'argv', ['robot_pipeline']),
              patch.dict(os.environ, {'COLUMNS': '80'})):
            try:
                pipeline_main([command, '--help'])
            except SystemExit as exc:
                if exc.code != 0:
                    raise
        lines += [f'### robot_pipeline {command}', '', '```text',
                  output.getvalue().rstrip(), '```', '']
    lines += ['## ROS launch arguments', '',
              'An empty declared default can be resolved from YAML or an installed package',
              'by the launch setup function; it is not necessarily the effective runtime value.', '']
    for path in sorted((ROOT / 'src/arm_lab_bringup/launch').glob('*.launch.py')):
        lines += [f'### {path.name}', '', f'[Source]({source_link(path)})', '',
                  '| Argument | Declared default | Description |', '|---|---|---|']
        for node in ast.walk(tree(path)):
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) and node.func.id == 'DeclareLaunchArgument':
                values = {k.arg: ast.literal_eval(k.value) for k in node.keywords}
                name = ast.literal_eval(node.args[0])
                lines.append(f"| `{name}` | `{cell(repr(values.get('default_value', '')))}` | {cell(values.get('description', 'See launch source.'))} |")
        lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


def config_values():
    path = ROOT / 'src/arm_lab_model/config/arm_config.yaml'
    raw = yaml.safe_load(path.read_text())
    lines = ['# Shipped configuration values', '', HEADER,
             f'Source: [arm_config.yaml]({source_link(path)}). These are **example values**,',
             'not loader defaults or recommended component specifications. See',
             '[Configuration](CONFIGURATION.md) for units, validation and optional measured inertials.', '',
             'Library entries and joints are listed individually so every shipped value is visible.', '']

    def flatten(node, prefix):
        if isinstance(node, dict):
            for key, value in node.items():
                yield from flatten(value, f'{prefix}.{key}' if prefix else str(key))
        elif isinstance(node, list) and node and isinstance(node[0], dict):
            for index, value in enumerate(node):
                yield from flatten(value, f'{prefix}[{index}]')
        else:
            yield prefix, repr(node)

    for section, value in raw.items():
        lines += [f'## {section}', '', '| Path | Shipped value |', '|---|---|']
        lines += [f'| `{cell(key)}` | `{cell(val)}` |' for key, val in flatten(value, section)]
        lines.append('')
    return '\n'.join(lines).rstrip() + '\n'


def api_reference():
    lines = ['# Core Python API reference', '', HEADER,
             'Signatures and summaries are extracted without executing the modules.',
             'This covers public definitions in the core model, export and report modules;',
             '[Domain models](DOMAIN_MODELS.md) explains ownership and semantics.',
             'Dataclass fields without defaults must be supplied by callers; normal users',
             'should call `load_config` instead of constructing the aggregate manually.', '']
    modules = ['config', 'project_config', 'robot_topology', 'mesh_physics', 'physical_robot',
               'robot_legacy', 'robot_export', 'pipeline_options', 'pipeline_runtime', 'pipeline_cli',
               'joint_trajectory', 'trajectory_store', 'scene_config', 'sensor_runtime', 'perception',
               'benchmark_reference', 'benchmark_observations', 'benchmark_engine', 'benchmark_reports',
               'kinematics', 'actuator_model', 'mujoco_backend', 'urdf_builder', 'controllers_builder',
               'spec_report', 'verification', 'system', 'structures']
    module_paths = [('arm_lab_model', module) for module in modules]
    module_paths += [('arm_lab_kinematics', module) for module in ('pipeline_moveit', 'pipeline_target')]
    module_paths += [('arm_lab_gui', module) for module in
                     ('pipeline_scene', 'pipeline_perception', 'pipeline_sim_node')]
    for package, module in module_paths:
        path = ROOT / 'src' / package / package / (module + '.py')
        lines += [f'## {module}', '', f'[Source]({source_link(path)})', '']
        for node in tree(path).body:
            if not isinstance(node, (ast.ClassDef, ast.FunctionDef)) or node.name.startswith('_'):
                continue
            lines += [f'### {node.name}', '']
            doc = ast.get_docstring(node)
            if doc:
                lines += [' '.join(doc.split('\n\n', 1)[0].splitlines()), '']
            members = node.body if isinstance(node, ast.ClassDef) else [node]
            fields = [m for m in members if isinstance(m, ast.AnnAssign) and isinstance(m.target, ast.Name)]
            if fields:
                lines += ['| Field | Type | Declared default |', '|---|---|---|']
                for m in fields:
                    default = ast.unparse(m.value) if m.value is not None else 'required'
                    lines.append(f'| `{m.target.id}` | `{cell(ast.unparse(m.annotation))}` | `{cell(default)}` |')
                lines.append('')
            functions = [m for m in members if isinstance(m, ast.FunctionDef) and (not m.name.startswith('_') or m.name == '__init__')]
            if functions:
                lines += ['```python']
                for m in functions:
                    for decorator in m.decorator_list:
                        if isinstance(decorator, ast.Name) and decorator.id in ('property', 'staticmethod', 'classmethod'):
                            lines.append('@' + decorator.id)
                    returns = ' -> ' + ast.unparse(m.returns) if m.returns else ''
                    lines.append(f'def {m.name}({ast.unparse(m.args)}){returns}: ...')
                lines += ['```', '']
    return '\n'.join(lines).rstrip() + '\n'


def diagram_embeds(path):
    text = path.read_text()
    pattern = r'<!-- AUTO-GENERATED: diagram:([a-z-]+) -->.*?<!-- END AUTO-GENERATED -->'
    def replace(match):
        source = ROOT / 'docs/diagrams' / (match[1] + '.mmd')
        return (f'<!-- AUTO-GENERATED: diagram:{match[1]} -->\n\n```mermaid\n'
                + source.read_text().rstrip() + '\n```\n\n<!-- END AUTO-GENERATED -->')
    return re.sub(pattern, replace, text, flags=re.S)


def check_links():
    errors = []
    paths = [ROOT / 'README.md', ROOT / 'CONTRIBUTING.md', *sorted((ROOT / 'docs').rglob('*.md'))]
    for path in paths:
        for target in re.findall(r'\]\(([^)]+)\)', path.read_text()):
            if re.match(r'[a-zA-Z][a-zA-Z0-9+.-]*:', target) or target.startswith('#'):
                continue
            target = target.split('#', 1)[0].strip('<>')
            if target and not (path.parent / target).exists():
                errors.append(f'{path.relative_to(ROOT)}: missing link {target}')
    return errors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    outputs = {ROOT / 'docs/COMMANDS.md': commands(),
               ROOT / 'docs/CONFIG_VALUES.md': config_values(),
               ROOT / 'docs/API_REFERENCE.md': api_reference()}
    for path in sorted((ROOT / 'docs').glob('*.md')):
        if path not in outputs:
            outputs[path] = diagram_embeds(path)
    drift = []
    for path, content in outputs.items():
        if not path.exists() or path.read_text() != content:
            drift.append(str(path.relative_to(ROOT)))
            if not args.check:
                path.write_text(content)
    errors = check_links()
    if args.check and drift:
        errors += ['Generated documentation is stale: ' + ', '.join(drift)]
    if errors:
        print('\n'.join(errors), file=sys.stderr)
        return 1
    print('Documentation is current; local file links resolve.' if args.check else
          f'Updated {len(drift)} documentation files; local file links resolve.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
