"""Generate the ros2_control controller manager YAML from the arm config.

Joint names, limits and PID gains all come from the same YAML that builds the
URDF, so adding or removing a joint needs no edits anywhere else.
"""

from __future__ import annotations

from typing import Any, Dict, Optional

import yaml

from .config import ArmConfig

class _NoAliasDumper(yaml.SafeDumper):
    """rcl's YAML parser rejects anchors and aliases, so never emit them."""

    def ignore_aliases(self, data):
        return True


ARM_CONTROLLER = 'arm_controller'
GRIPPER_CONTROLLER = 'gripper_controller'
SPEED_CONTROLLER = 'arm_velocity_controller'


def _gains(cfg: ArmConfig, command_interface: str) -> Dict[str, Any]:
    """PID gains for the trajectory controller's inner loop.

    Only needed when the command interface is not position: the controller then
    has to close the loop itself.
    """
    g = cfg.control.get('gains', {})
    p_scale = float(g.get('p_scale', 12.0))
    i_scale = float(g.get('i_scale', 0.4))
    d_scale = float(g.get('d_scale', 1.2))
    i_clamp = float(g.get('i_clamp', 8.0))

    out: Dict[str, Any] = {}
    for joint in cfg.joints:
        if command_interface == 'effort':
            # Torque per radian of error: scale with what the joint can deliver.
            p = p_scale * joint.effort_limit
            out[joint.name] = {
                'p': round(p, 3),
                'i': round(i_scale * p * 0.05, 4),
                'd': round(d_scale * p * 0.08, 4),
                'i_clamp': round(i_clamp / 8.0 * joint.effort_limit * 0.5, 3),
                'ff_velocity_scale': 0.0,
            }
        else:
            # Velocity per radian of error, i.e. a 1/s gain. The integral term
            # is what removes steady-state droop: without enough of it the arm
            # holds a pose tens of millimetres below the one it was asked for,
            # which is invisible until something has to be grasped.
            out[joint.name] = {
                'p': round(p_scale, 4),
                'i': round(i_scale, 4),
                'd': round(d_scale * 0.05, 4),
                'i_clamp': round(i_clamp * 0.1, 4),
                'ff_velocity_scale': 1.0,
            }
    return out


def build_controllers(cfg: ArmConfig,
                      command_interface: Optional[str] = None,
                      use_sim_time: bool = True) -> Dict[str, Any]:
    ci = command_interface or cfg.control.get('command_interface', 'velocity')
    if ci not in ('position', 'velocity', 'effort'):
        raise ValueError(f'command_interface must be position|velocity|effort, got {ci}')

    rate = int(cfg.control.get('update_rate', 200))
    joint_names = cfg.joint_names
    finger_joints = cfg.end_effector.finger_joint_names

    manager: Dict[str, Any] = {
        'update_rate': rate,
        'use_sim_time': use_sim_time,
        'joint_state_broadcaster': {
            'type': 'joint_state_broadcaster/JointStateBroadcaster'},
        ARM_CONTROLLER: {
            'type': 'joint_trajectory_controller/JointTrajectoryController'},
    }
    if finger_joints:
        manager[GRIPPER_CONTROLLER] = {
            'type': ('effort_controllers/JointGroupEffortController'
                     if cfg.end_effector.grasp_mode == 'force'
                     else 'position_controllers/JointGroupPositionController')}
    if ci == 'velocity':
        # Spare controller for raw speed sweeps; started on demand.
        manager[SPEED_CONTROLLER] = {
            'type': 'velocity_controllers/JointGroupVelocityController'}

    arm: Dict[str, Any] = {
        'joints': list(joint_names),
        'command_interfaces': [ci],
        'state_interfaces': ['position', 'velocity'],
        'allow_partial_joints_goal': True,
        'allow_nonzero_velocity_at_trajectory_end': True,
        'open_loop_control': False,
        'interpolation_method': 'splines',
        'action_monitor_rate': 25.0,
        'constraints': {
            'stopped_velocity_tolerance': 0.02,
            'goal_time': 2.0,
        },
    }
    for joint in cfg.joints:
        arm['constraints'][joint.name] = {'trajectory': 0.0, 'goal': 0.0}
    if ci != 'position':
        arm['gains'] = _gains(cfg, ci)

    params: Dict[str, Any] = {
        'controller_manager': {'ros__parameters': manager},
        ARM_CONTROLLER: {'ros__parameters': dict(arm, use_sim_time=use_sim_time)},
    }
    if finger_joints:
        params[GRIPPER_CONTROLLER] = {'ros__parameters': {
            'joints': list(finger_joints),
            'use_sim_time': use_sim_time,
        }}
    if SPEED_CONTROLLER in manager:
        params[SPEED_CONTROLLER] = {'ros__parameters': {
            'joints': list(joint_names),
            'use_sim_time': use_sim_time,
        }}
    return params


def dump_controllers(cfg: ArmConfig, path: str, **kwargs) -> str:
    data = build_controllers(cfg, **kwargs)
    header = (f'# generated by arm_lab_model from {cfg.source_path}\n'
              f'# DO NOT EDIT: change the YAML config and re-launch instead\n')
    with open(path, 'w') as fh:
        fh.write(header)
        yaml.dump(data, fh, Dumper=_NoAliasDumper, sort_keys=False,
                  default_flow_style=False)
    return path
